In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import math

In [2]:
df = pd.read_csv('datafile (1).csv')

In [3]:
df

,Crop,State,Cost of Cultivation (`/Hectare) A2+FL,Cost of Cultivation (`/Hectare) C2,Cost of Production (`/Quintal) C2,Yield (Quintal/ Hectare)
0,ARHAR,Uttar Pradesh,9794.05,23076.74,1941.55,9.83
1,ARHAR,Karnataka,10593.15,16528.68,2172.46,7.47
2,ARHAR,Gujarat,13468.82,19551.90,1898.30,9.59
3,ARHAR,Andhra Pradesh,17051.66,24171.65,3670.54,6.42
4,ARHAR,Maharashtra,17130.55,25270.26,2775.80,8.72
5,COTTON,Maharashtra,23711.44,33116.82,2539.47,12.69
6,COTTON,Punjab,29047.10,50828.83,2003.76,24.39
7,COTTON,Andhra Pradesh,29140.77,44756.72,2509.99,17.83
8,COTTON,Gujarat,29616.09,42070.44,2179.26,19.05
9,COTTON,Haryana,29918.97,44018.18,2127.35,19.90
10,GRAM,Rajasthan,8552.69,12610.85,1691.66,6.83
11,GRAM,Madhya Pradesh,9803.89,16873.17,1551.94,10.29
12,GRAM,Uttar Pradesh,12833.04,21618.43,1882.68,10.93
13,GRAM,Maharashtra,12985.95,18679.33,2277.68,8.05
14,GRAM,Andhra Pradesh,14421.98,26762.09,1559.04,16.69
15,GROUNDNUT,Karnataka,13647.10,17314.20,3484.01,4.71
16,GROUNDNUT,Andhra Pradesh,21229.01,30434.61,2554.91,11.97
17,GROUNDNUT,Tamil Nadu,22507.86,30393.66,2358.00,11.98
18,GROUNDNUT,Gujarat,22951.28,30114.45,1918.92,13.45
19,GROUNDNUT,Maharashtra,26078.66,32683.46,3207.35,9.33
20,MAIZE,Bihar,13513.92,19857.70,404.43,42.95
21,MAIZE,Karnataka,13792.85,20671.54,581.69,31.10
22,MAIZE,Rajasthan,14421.46,19810.29,658.77,23.56
23,MAIZE,Uttar Pradesh,15635.43,21045.11,1387.36,13.70
24,MAIZE,Andhra Pradesh,25687.09,37801.85,840.58,42.68
25,MOONG,Orissa,5483.54,8266.98,2614.14,3.01
26,MOONG,Rajasthan,6204.23,9165.59,2068.67,4.05
27,MOONG,Karnataka,6440.64,7868.64,5777.48,1.32
28,MOONG,Andhra Pradesh,6684.18,13209.32,2228.97,5.90
29,MOONG,Maharashtra,10780.76,15371.45,2261.24,6.70
30,PADDY,Uttar Pradesh,17022.00,28144.50,732.62,36.61
31,PADDY,Orissa,17478.05,25909.05,715.04,32.42
32,PADDY,West Bengal,24731.06,33046.12,731.25,39.04
33,PADDY,Punjab,25154.75,45291.24,669.86,67.41
34,PADDY,Andhra Pradesh,29664.84,46450.20,789.90,56.00
35,RAPESEED AND MUSTARD,Madhya Pradesh,8686.43,17705.93,1279.60,12.94
36,RAPESEED AND MUSTARD,Rajasthan,11385.70,19259.84,1341.29,13.54
37,RAPESEED AND MUSTARD,Uttar Pradesh,12774.41,22560.30,1595.56,13.57
38,RAPESEED AND MUSTARD,Gujarat,13740.64,19083.55,1610.40,11.61
39,RAPESEED AND MUSTARD,Haryana,14715.27,27507.54,1251.12,19.94
40,SUGARCANE,Uttar Pradesh,24538.32,45239.51,93.64,448.89
41,SUGARCANE,Karnataka,55655.44,86765.77,86.53,986.21
42,SUGARCANE,Andhra Pradesh,56621.16,91442.63,119.72,757.92
43,SUGARCANE,Maharashtra,57673.60,85801.95,107.56,744.01
44,SUGARCANE,Tamil Nadu,66335.06,89025.27,85.79,1015.45
45,WHEAT,Madhya Pradesh,12464.40,22489.75,810.25,23.59
46,WHEAT,Punjab,17945.58,35423.48,804.80,39.83
47,WHEAT,Uttar Pradesh,18979.38,31902.74,769.84,34.99
48,WHEAT,Rajasthan,19119.08,29876.36,683.58,37.19

In [12]:
crops = df.groupby(['Crop','State'])

In [13]:
crops

In [14]:
df.describe()

,Cost of Cultivation (`/Hectare) A2+FL,Cost of Cultivation (`/Hectare) C2,Cost of Production (`/Quintal) C2,Yield (Quintal/ Hectare)
count,49.000000,49.000000,49.000000,49.000000
mean,20363.537347,31364.666735,1620.537755,98.086735
std,13561.435306,20095.783569,1104.990472,245.293123
min,5483.540000,7868.640000,85.790000,1.320000
25%,12774.410000,19259.840000,732.620000,9.590000
50%,17022.000000,25909.050000,1595.560000,13.700000
75%,24731.060000,35423.480000,2228.970000,36.610000
max,66335.060000,91442.630000,5777.480000,1015.450000

In [23]:
crops.first()

                                     Cost of Cultivation (`/Hectare) A2+FL  \
Crop                 State
ARHAR                Andhra Pradesh                               17051.66
                     Gujarat                                      13468.82
                     Karnataka                                    10593.15
                     Maharashtra                                  17130.55
                     Uttar Pradesh                                 9794.05
COTTON               Andhra Pradesh                               29140.77
                     Gujarat                                      29616.09
                     Haryana                                      29918.97
                     Maharashtra                                  23711.44
                     Punjab                                       29047.10
GRAM                 Andhra Pradesh                               14421.98
                     Madhya Pradesh                                9803.89
                     Maharashtra                                  12985.95
                     Rajasthan                                     8552.69
                     Uttar Pradesh                                12833.04
GROUNDNUT            Andhra Pradesh                               21229.01
                     Gujarat                                      22951.28
                     Karnataka                                    13647.10
                     Maharashtra                                  26078.66
                     Tamil Nadu                                   22507.86
MAIZE                Andhra Pradesh                               25687.09
                     Bihar                                        13513.92
                     Karnataka                                    13792.85
                     Rajasthan                                    14421.46
                     Uttar Pradesh                                15635.43
MOONG                Andhra Pradesh                                6684.18
                     Karnataka                                     6440.64
                     Maharashtra                                  10780.76
                     Orissa                                        5483.54
                     Rajasthan                                     6204.23
PADDY                Andhra Pradesh                               29664.84
                     Orissa                                       17478.05
                     Punjab                                       25154.75
                     Uttar Pradesh                                17022.00
                     West Bengal                                  24731.06
RAPESEED AND MUSTARD Gujarat                                      13740.64
                     Haryana                                      14715.27
                     Madhya Pradesh                                8686.43
                     Rajasthan                                    11385.70
                     Uttar Pradesh                                12774.41
SUGARCANE            Andhra Pradesh                               56621.16
                     Karnataka                                    55655.44
                     Maharashtra                                  57673.60
                     Tamil Nadu                                   66335.06
                     Uttar Pradesh                                24538.32
WHEAT                Madhya Pradesh                               12464.40
                     Punjab                                       17945.58
                     Rajasthan                                    19119.08
                     Uttar Pradesh                                18979.38

                                     Cost of Cultivation (`/Hectare) C2  \
Crop                 State
ARHAR                Andhra Pradesh                            24171.65
                     Gujarat                                   19551.90
                     Karnataka                                 16528.68
                     Maharashtra                               25270.26
                     Uttar Pradesh                             23076.74
COTTON               Andhra Pradesh                            44756.72
                     Gujarat                                   42070.44
                     Haryana                                   44018.18
                     Maharashtra                               33116.82
                     Punjab                                    50828.83
GRAM                 Andhra Pradesh                            26762.09
                     Madhya Pradesh                            16873.17
                     Maharashtra                               18679.33
                     Rajasthan                                 12610.85
                     Uttar Pradesh                             21618.43
GROUNDNUT            Andhra Pradesh                            30434.61
                     Gujarat                                   30114.45
                     Karnataka                                 17314.20
                     Maharashtra                               32683.46
                     Tamil Nadu                                30393.66
MAIZE                Andhra Pradesh                            37801.85
                     Bihar                                     19857.70
                     Karnataka                                 20671.54
                     Rajasthan                                 19810.29
                     Uttar Pradesh                             21045.11
MOONG                Andhra Pradesh                            13209.32
                     Karnataka                                  7868.64
                     Maharashtra                               15371.45
                     Orissa                                     8266.98
                     Rajasthan                                  9165.59
PADDY                Andhra Pradesh                            46450.20
                     Orissa                                    25909.05
                     Punjab                                    45291.24
                     Uttar Pradesh                             28144.50
                     West Bengal                               33046.12
RAPESEED AND MUSTARD Gujarat                                   19083.55
                     Haryana                                   27507.54
                     Madhya Pradesh                            17705.93
                     Rajasthan                                 19259.84
                     Uttar Pradesh                             22560.30
SUGARCANE            Andhra Pradesh                            91442.63
                     Karnataka                                 86765.77
                     Maharashtra                               85801.95
                     Tamil Nadu                                89025.27
                     Uttar Pradesh                             45239.51
WHEAT                Madhya Pradesh                            22489.75
                     Punjab                                    35423.48
                     Rajasthan                                 29876.36
                     Uttar Pradesh                             31902.74

                                     Cost of Production (`/Quintal) C2  \
Crop                 State
ARHAR                Andhra Pradesh                            3670.54
                     Gujarat                                   1898.30
                     Karnataka                                 2172.46
                     Maharashtra                               2775.80
                     Uttar Pradesh                             1941.55
COTTON               Andhra Pradesh                            2509.99
                     Gujarat                                   2179.26
                     Haryana                                   2127.35
                     Maharashtra                               2539.47
                     Punjab                                    2003.76
GRAM                 Andhra Pradesh                            1559.04
                     Madhya Pradesh                            1551.94
                     Maharashtra                               2277.68
                     Rajasthan                                 1691.66
                     Uttar Pradesh                             1882.68
GROUNDNUT            Andhra Pradesh                            2554.91
                     Gujarat                                   1918.92
                     Karnataka                                 3484.01
                     Maharashtra                               3207.35
                     Tamil Nadu                                2358.00
MAIZE                Andhra Pradesh                             840.58
                     Bihar                                      404.43
                     Karnataka                                  581.69
                     Rajasthan                                  658.77
                     Uttar Pradesh                             1387.36
MOONG                Andhra Pradesh                            2228.97
                     Karnataka                                 5777.48
                     Maharashtra                               2261.24
                     Orissa                                    2614.14
                     Rajasthan                                 2068.67
PADDY                Andhra Pradesh                             789.90
                     Orissa                                     715.04
                     Punjab                                     669.86
                     Uttar Pradesh                              732.62
                     West Bengal                                731.25
RAPESEED AND MUSTARD Gujarat                                   1610.40
                     Haryana                                   1251.12
                     Madhya Pradesh                            1279.60
                     Rajasthan                                 1341.29
                     Uttar Pradesh                             1595.56
SUGARCANE            Andhra Pradesh                             119.72
                     Karnataka                                   86.53
                     Maharashtra                                107.56
                     Tamil Nadu                                  85.79
                     Uttar Pradesh                               93.64
WHEAT                Madhya Pradesh                             810.25
                     Punjab                                     804.80
                     Rajasthan                                  683.58
                     Uttar Pradesh                              769.84

                                     Yield (Quintal/ Hectare)
Crop                 State
ARHAR                Andhra Pradesh                       6.42
                     Gujarat                              9.59
                     Karnataka                            7.47
                     Maharashtra                          8.72
                     Uttar Pradesh                        9.83
COTTON               Andhra Pradesh                      17.83
                     Gujarat                             19.05
                     Haryana                             19.90
                     Maharashtra                         12.69
                     Punjab                              24.39
GRAM                 Andhra Pradesh                      16.69
                     Madhya Pradesh                      10.29
                     Maharashtra                          8.05
                     Rajasthan                            6.83
                     Uttar Pradesh                       10.93
GROUNDNUT            Andhra Pradesh                      11.97
                     Gujarat                             13.45
                     Karnataka                            4.71
                     Maharashtra                          9.33
                     Tamil Nadu                          11.98
MAIZE                Andhra Pradesh                      42.68
                     Bihar                               42.95
                     Karnataka                           31.10
                     Rajasthan                           23.56
                     Uttar Pradesh                       13.70
MOONG                Andhra Pradesh                       5.90
                     Karnataka                            1.32
                     Maharashtra                          6.70
                     Orissa                               3.01
                     Rajasthan                            4.05
PADDY                Andhra Pradesh                      56.00
                     Orissa                              32.42
                     Punjab                              67.41
                     Uttar Pradesh                       36.61
                     West Bengal                         39.04
RAPESEED AND MUSTARD Gujarat                             11.61
                     Haryana                             19.94
                     Madhya Pradesh                      12.94
                     Rajasthan                           13.54
                     Uttar Pradesh                       13.57
SUGARCANE            Andhra Pradesh                     757.92
                     Karnataka                          986.21
                     Maharashtra                        744.01
                     Tamil Nadu                        1015.45
                     Uttar Pradesh                      448.89
WHEAT                Madhya Pradesh                      23.59
                     Punjab                              39.83
                     Rajasthan                           37.19
                     Uttar Pradesh                       34.99

In [25]:
state_crops = crops.first()
state_crops

                                     Cost of Cultivation (`/Hectare) A2+FL  \
Crop                 State
ARHAR                Andhra Pradesh                               17051.66
                     Gujarat                                      13468.82
                     Karnataka                                    10593.15
                     Maharashtra                                  17130.55
                     Uttar Pradesh                                 9794.05
COTTON               Andhra Pradesh                               29140.77
                     Gujarat                                      29616.09
                     Haryana                                      29918.97
                     Maharashtra                                  23711.44
                     Punjab                                       29047.10
GRAM                 Andhra Pradesh                               14421.98
                     Madhya Pradesh                                9803.89
                     Maharashtra                                  12985.95
                     Rajasthan                                     8552.69
                     Uttar Pradesh                                12833.04
GROUNDNUT            Andhra Pradesh                               21229.01
                     Gujarat                                      22951.28
                     Karnataka                                    13647.10
                     Maharashtra                                  26078.66
                     Tamil Nadu                                   22507.86
MAIZE                Andhra Pradesh                               25687.09
                     Bihar                                        13513.92
                     Karnataka                                    13792.85
                     Rajasthan                                    14421.46
                     Uttar Pradesh                                15635.43
MOONG                Andhra Pradesh                                6684.18
                     Karnataka                                     6440.64
                     Maharashtra                                  10780.76
                     Orissa                                        5483.54
                     Rajasthan                                     6204.23
PADDY                Andhra Pradesh                               29664.84
                     Orissa                                       17478.05
                     Punjab                                       25154.75
                     Uttar Pradesh                                17022.00
                     West Bengal                                  24731.06
RAPESEED AND MUSTARD Gujarat                                      13740.64
                     Haryana                                      14715.27
                     Madhya Pradesh                                8686.43
                     Rajasthan                                    11385.70
                     Uttar Pradesh                                12774.41
SUGARCANE            Andhra Pradesh                               56621.16
                     Karnataka                                    55655.44
                     Maharashtra                                  57673.60
                     Tamil Nadu                                   66335.06
                     Uttar Pradesh                                24538.32
WHEAT                Madhya Pradesh                               12464.40
                     Punjab                                       17945.58
                     Rajasthan                                    19119.08
                     Uttar Pradesh                                18979.38

                                     Cost of Cultivation (`/Hectare) C2  \
Crop                 State
ARHAR                Andhra Pradesh                            24171.65
                     Gujarat                                   19551.90
                     Karnataka                                 16528.68
                     Maharashtra                               25270.26
                     Uttar Pradesh                             23076.74
COTTON               Andhra Pradesh                            44756.72
                     Gujarat                                   42070.44
                     Haryana                                   44018.18
                     Maharashtra                               33116.82
                     Punjab                                    50828.83
GRAM                 Andhra Pradesh                            26762.09
                     Madhya Pradesh                            16873.17
                     Maharashtra                               18679.33
                     Rajasthan                                 12610.85
                     Uttar Pradesh                             21618.43
GROUNDNUT            Andhra Pradesh                            30434.61
                     Gujarat                                   30114.45
                     Karnataka                                 17314.20
                     Maharashtra                               32683.46
                     Tamil Nadu                                30393.66
MAIZE                Andhra Pradesh                            37801.85
                     Bihar                                     19857.70
                     Karnataka                                 20671.54
                     Rajasthan                                 19810.29
                     Uttar Pradesh                             21045.11
MOONG                Andhra Pradesh                            13209.32
                     Karnataka                                  7868.64
                     Maharashtra                               15371.45
                     Orissa                                     8266.98
                     Rajasthan                                  9165.59
PADDY                Andhra Pradesh                            46450.20
                     Orissa                                    25909.05
                     Punjab                                    45291.24
                     Uttar Pradesh                             28144.50
                     West Bengal                               33046.12
RAPESEED AND MUSTARD Gujarat                                   19083.55
                     Haryana                                   27507.54
                     Madhya Pradesh                            17705.93
                     Rajasthan                                 19259.84
                     Uttar Pradesh                             22560.30
SUGARCANE            Andhra Pradesh                            91442.63
                     Karnataka                                 86765.77
                     Maharashtra                               85801.95
                     Tamil Nadu                                89025.27
                     Uttar Pradesh                             45239.51
WHEAT                Madhya Pradesh                            22489.75
                     Punjab                                    35423.48
                     Rajasthan                                 29876.36
                     Uttar Pradesh                             31902.74

                                     Cost of Production (`/Quintal) C2  \
Crop                 State
ARHAR                Andhra Pradesh                            3670.54
                     Gujarat                                   1898.30
                     Karnataka                                 2172.46
                     Maharashtra                               2775.80
                     Uttar Pradesh                             1941.55
COTTON               Andhra Pradesh                            2509.99
                     Gujarat                                   2179.26
                     Haryana                                   2127.35
                     Maharashtra                               2539.47
                     Punjab                                    2003.76
GRAM                 Andhra Pradesh                            1559.04
                     Madhya Pradesh                            1551.94
                     Maharashtra                               2277.68
                     Rajasthan                                 1691.66
                     Uttar Pradesh                             1882.68
GROUNDNUT            Andhra Pradesh                            2554.91
                     Gujarat                                   1918.92
                     Karnataka                                 3484.01
                     Maharashtra                               3207.35
                     Tamil Nadu                                2358.00
MAIZE                Andhra Pradesh                             840.58
                     Bihar                                      404.43
                     Karnataka                                  581.69
                     Rajasthan                                  658.77
                     Uttar Pradesh                             1387.36
MOONG                Andhra Pradesh                            2228.97
                     Karnataka                                 5777.48
                     Maharashtra                               2261.24
                     Orissa                                    2614.14
                     Rajasthan                                 2068.67
PADDY                Andhra Pradesh                             789.90
                     Orissa                                     715.04
                     Punjab                                     669.86
                     Uttar Pradesh                              732.62
                     West Bengal                                731.25
RAPESEED AND MUSTARD Gujarat                                   1610.40
                     Haryana                                   1251.12
                     Madhya Pradesh                            1279.60
                     Rajasthan                                 1341.29
                     Uttar Pradesh                             1595.56
SUGARCANE            Andhra Pradesh                             119.72
                     Karnataka                                   86.53
                     Maharashtra                                107.56
                     Tamil Nadu                                  85.79
                     Uttar Pradesh                               93.64
WHEAT                Madhya Pradesh                             810.25
                     Punjab                                     804.80
                     Rajasthan                                  683.58
                     Uttar Pradesh                              769.84

                                     Yield (Quintal/ Hectare)
Crop                 State
ARHAR                Andhra Pradesh                       6.42
                     Gujarat                              9.59
                     Karnataka                            7.47
                     Maharashtra                          8.72
                     Uttar Pradesh                        9.83
COTTON               Andhra Pradesh                      17.83
                     Gujarat                             19.05
                     Haryana                             19.90
                     Maharashtra                         12.69
                     Punjab                              24.39
GRAM                 Andhra Pradesh                      16.69
                     Madhya Pradesh                      10.29
                     Maharashtra                          8.05
                     Rajasthan                            6.83
                     Uttar Pradesh                       10.93
GROUNDNUT            Andhra Pradesh                      11.97
                     Gujarat                             13.45
                     Karnataka                            4.71
                     Maharashtra                          9.33
                     Tamil Nadu                          11.98
MAIZE                Andhra Pradesh                      42.68
                     Bihar                               42.95
                     Karnataka                           31.10
                     Rajasthan                           23.56
                     Uttar Pradesh                       13.70
MOONG                Andhra Pradesh                       5.90
                     Karnataka                            1.32
                     Maharashtra                          6.70
                     Orissa                               3.01
                     Rajasthan                            4.05
PADDY                Andhra Pradesh                      56.00
                     Orissa                              32.42
                     Punjab                              67.41
                     Uttar Pradesh                       36.61
                     West Bengal                         39.04
RAPESEED AND MUSTARD Gujarat                             11.61
                     Haryana                             19.94
                     Madhya Pradesh                      12.94
                     Rajasthan                           13.54
                     Uttar Pradesh                       13.57
SUGARCANE            Andhra Pradesh                     757.92
                     Karnataka                          986.21
                     Maharashtra                        744.01
                     Tamil Nadu                        1015.45
                     Uttar Pradesh                      448.89
WHEAT                Madhya Pradesh                      23.59
                     Punjab                              39.83
                     Rajasthan                           37.19
                     Uttar Pradesh                       34.99

KeyError: 'State'